### ISSUE TITLE
How to use pretrained models to get the results.

### ISSUE THREAD

**Issue by Rajratnpranesh** [tbepler/protein-sequence-embedding-iclr2019#15]
Hi! Thank you for open sourcing your work.

I am trying to generate the paper result. How exactly can I use the pretrained model to get the result? 
Thank You.

**Comment by tbepler** [comment]
Take a look at the various eval_XXX.py scripts to see how the pretrained model is used.

These other issues may also be helpful: #13, #1, #14

**Comment by Rajratnpranesh** [comment]
Thank you for your reply. I will look into it.
