### ISSUE TITLE
Using pre-trained models

### ISSUE THREAD

**Issue by mstrazar** [tbepler/protein-sequence-embedding-iclr2019#25]
Hi @tbepler ,
I managed to install your code and would like to use pre-trained models to embed 100,000s protein sequences. I tried `ssa_L1_100d_lstm3x512_lm_i512_mb64_tau0.5_p0.05_epoch100.sav` , but it appears to process only ~ 1 sequence per minute on top end CPU (no cuda).  If i understand correctly, sequences should just be passed through the network to get the embeddings, i.e. a fast operation.

Any ideas? Should I use other pre-trained models?

Thanks,
Martin

**Comment by tbepler** [comment]
Hi Martin,

Have you checked that pytorch is using all of your CPU cores? Is the number of cores limited for some reason?

I wouldn't expect the code to run super fast on CPU, but that does sound slow. If you have a GPU, I highly recommend using it! The code will run much faster.

For the embedding model, I suggest using the lambda0.1 model, but it won't change the runtime.

**Comment by mstrazar** [comment]
Just to confirm, a GPU machine and lambda0.1 model crank out 300 sequences per minute. Thanks, Martin

**Comment by tbepler** [comment]
Great, closing this issue.
