### ISSUE TITLE
Generating Fasta/Text file for different dataset

### ISSUE THREAD

**Issue by vsomnath** [tbepler/protein-sequence-embedding-iclr2019#26]
Hi, thank you for open sourcing this work. 

We currently want to utilize your pretrained models for finetuning on a binding affinity dataset. Any advice (or an existing script) on how one can generate fasta files (in the format your models use) for a new dataset would be appreciated.

**Comment by tbepler** [comment]
Fasta is the "standard" sequence file format and it's pretty simple. Take a look [here](https://en.wikipedia.org/wiki/FASTA_format) or [here](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) for examples.

The embedding script accepts files in the standard fasta format.
