### ISSUE TITLE
Available data

### ISSUE THREAD

**Issue by AxelGiottonini** [tbepler/protein-sequence-embedding-iclr2019#28]
Hey !
I would like to reuse your models without training them from scratch but it seems that the `bergerlab-downloads.csail.mit.edu` website is not responding anymore. Are there any other links where we could find the parameters for the pretrained model ?

**Comment by Joliver3991** [comment]
Hi, yes could you please provide a working link from which to download the pre-trained models. That would be great. Thanks.

**Comment by tbepler** [comment]
Thanks for reporting this. The link should be working again now.

**Comment by AxelGiottonini** [comment]
Wonderful ! Thanks a lot !
