### ISSUE TITLE
Language Model Accuracy on Pfam? 

### ISSUE THREAD

**Issue by nickbhat** [tbepler/protein-sequence-embedding-iclr2019#4]
I couldn't find the next-token prediction accuracy of the biLM in the paper. Would you mind sharing what you got after one epoch on Pfam as described in supplement A?

**Comment by tbepler** [comment]
It has about 29% next token accuracy on the held out sequences (and roughly the same on the training sequences). This will increase if the model is trained longer, but I didn't find that this made any difference when just using the hidden states as features for the structure-based embedding model.

**Comment by nickbhat** [comment]
What was the train/test split? Something like 90/10?

**Comment by tbepler** [comment]
I used an 80/20 split. You can download the exact split from the link in the README ([here](https://github.com/tbepler/protein-sequence-embedding-iclr2019#data-sets)).
