### ISSUE TITLE
1s in contact map?

### ISSUE THREAD

**Issue by thomas-a-neil** [tbepler/protein-sequence-embedding-iclr2019#5]
Hi,

Looking at how the contact map .pngs are loaded, I noticed that there seem to be two classes corresponding to pixel intensities 0 (no contact) and 255 (contact). There seems to be an additional class for pixel intensity = 1. All of those pixels are masked out (i.e. set to -1) https://github.com/tbepler/protein-sequence-embedding-iclr2019/blob/master/eval_contact_scop.py#L45 

What did this class correspond to?

Thank you for your help!

**Comment by tbepler** [comment]
Those are residues that were missing from the structure.

**Comment by thomas-a-neil** [comment]
I see, thank you!
