### ISSUE TITLE
Unable to load pretrained model?

### ISSUE THREAD

**Issue by YamamotoSayaka** [tbepler/protein-sequence-embedding-iclr2019#7]
Hi, thanks again for sharing this code.
However, I'm unable to load the pretrained model provided here.
It gives me the following error

> Traceback (most recent call last):
  File "eval_contact_casp12.py", line 462, in <module>
    main()
  File "eval_contact_casp12.py", line 326, in main
    model = torch.load(args.model)
  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x1f'.

BTW, I'm using python 3 and pytorch 0.4.1, training works fine for me.
Any suggestions?

**Comment by tbepler** [comment]
Are you still having this problem? If so, have you tried redownloading the model files? It's possible that this is due to corruption of the saved model file.

**Comment by YamamotoSayaka** [comment]
Hi @tbepler , unfortunately I'm still having this problem.
The file I downloaded is 495mb, and the md5 is f0decef5fe4e404398b7672f1c95fabd.
The only change I made in the code is to change '--model' flag to './pretrained_models.tar.gz'.

**Comment by tbepler** [comment]
Ah, you need to unzip the pretrained models first! There are a few pretrained models in that tar file.

**Comment by YamamotoSayaka** [comment]
@tbepler ahhh I get it. Many thanks!
Thought that I can direcly torch.load from it
