### ISSUE TITLE
Data download not working

### ISSUE THREAD

**Issue by vijec** [tbepler/protein-sequence-embedding-iclr2019#9]
It seems like the data download is not working. 

For example:
 wget http://bergerlab-downloads.csail.mit.edu/bepler-protein-sequence-embeddings-from-structure-iclr2019/pfam.tar.gz terminates with a HTTP 503 error.

**Comment by tbepler** [comment]
There may have been a temporary connection error with the download server. The link is working for me.

**Comment by vijec** [comment]
Works now, thanks!
